<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/style.css">
    <title>Afiichage</title>
</head>

<body>
    <header class="nav">
        <a href="#" class="nav__logo">
            <img src="img/logo.svg" alt="logo">
        </a>
        <ul class="nav__menu">
            <li><a href="#">Mes achats</a></li>
            <li><a href="#">Nouveau produit</a></li>
            <li><a href="#">Mes produits</a></li>
            <li><a href="#">Mon stock</a></li>
            <li><button>Nous contacter</button></li>
            <li><button>Connexion</button></li>
        </ul>
        <button class="nav__burger">
            <span></span>
        </button>
    </header>


    <main>

        <section class="img_mini_menu">
            <div class="search">
                <p><i class="fas fa-search"></i> <input type="text" class="search_input" placeholder="search" name="search"></p>
            </div>

            <section class="img_mini_menu_sous">


                <ul class="mini_menu">
                    <li><a href="#" class="mini_menu_tous">Tous</a></li>
                    <li><a href="#" class="mini_menu_refrigirateur">Réfrigirateur</a></li>
                    <li><a href="#" class="mini_menu_placard">Placard</a></li>
                    <li><a href="#" class="mini_menu_congélateur">Congélateur</a></li>
                    <li><a href="#" class="mini_menu_comptoir">Comptoir</a></li>
                    <li><a href="#" class="mini_menu_cave">Cave</a></li>
                </ul>

                <div class="afficheImage">
                    <!--<div class="afficheImage_par_trois">-->
                        <article>
                            <!--<div>-->
                                <img src="https://via.placeholder.com/300" alt="pomme" title="pomme" srcset="">
                            <!--</div>-->
                            <p>quelque chose</p>
                        </article>
                        <article>
                            <div>
                                <img src="https://via.placeholder.com/300" alt="IMG" srcset=""><!--
                                --><p>quelque chose</p>
                            </div>
                            
                        </article>
                        <article>
                            <div>
                                <img src="https://via.placeholder.com/300" alt="IMG" srcset="">
                            </div>
                            <p>quelque chose</p>
                        </article>
                    <!--</div>-->

                    <!--<div class="afficheImage_par_trois">-->
                        <article>
                            <div>
                                <img src="https://via.placeholder.com/300" alt="IMG" srcset="">
                            </div>
                            <p>quelque chose</p>
                        </article>
                        <article>
                            <div>
                                <img src="https://via.placeholder.com/300" alt="IMG" srcset="">
                            </div>
                            <p>quelque chose</p>
                        </article>
                        <article>
                            <div>
                                <img src="https://via.placeholder.com/300" alt="IMG" srcset="">
                            </div>
                            <p>quelque chose</p>
                        </article>
                    <!--</div>-->

                    <!--<div class="afficheImage_par_trois">-->
                        <article>
                            <div>
                                <img src="https://via.placeholder.com/300" alt="IMG" srcset="">
                            </div>
                            <p>quelque chose</p>
                        </article>
                        <article>
                            <div>
                                <img src="https://via.placeholder.com/300" alt="IMG" srcset=""> 
                            </div>
                            <p>quelque chose</p>
                        </article>
                        <article>
                            <div>
                                <img src="https://via.placeholder.com/300" alt="IMG" srcset="">
                            </div>
                            <p>quelque chose</p>
                        </article>
                    <!--</div>-->

                    <!--<div class="afficheImage_par_trois">-->
                        <article>
                            <div>
                                <img src="https://via.placeholder.com/300" alt="IMG" srcset="">
                            </div>
                            <p>quelque chose</p>
                        </article>
                        <article>
                            <div>
                                <img src="https://via.placeholder.com/300" alt="IMG" srcset="">
                            </div>
                            <p>quelque chose</p>
                        </article>
                        <article>
                            <div>
                                <img src="https://via.placeholder.com/300" alt="IMG" srcset="">
                            </div>
                            <p>quelque chose</p>
                        </article>
                    <!--</div>-->

                    <!--<div class="afficheImage_par_trois">-->
                        <article>
                            <div>
                                <img src="https://via.placeholder.com/300" alt="IMG" srcset="">
                            </div>
                            <p>quelque chose</p>
                        </article>
                        <article>
                            <div>
                                <img src="https://via.placeholder.com/300" alt="IMG" srcset="">
                            </div>
                            <p>quelque chose</p>
                        </article>
                        <article>
                            <div>
                                <img src="https://via.placeholder.com/300" alt="IMG" srcset="">
                            </div>
                            <p>quelque chose</p>
                        </article>
                    <!--</div>-->
                </div>


                <div class="img_mini_menu_sous_pagination">
                    <ul>
                        <li id="pagination_active">01</li>
                        <li>02</li>
                        <li>03</li>
                        <li>...</li>
                        <li>Next</li>
                    </ul>
                </div>
            </section>
        </section>

    </main>

</body>

</html>