<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>FreshFood-Detais</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="./css/decoupe/_details.css" rel="stylesheet">
</head>

<body class="box_body">

    <div class="box">
        <div class="box_haut">

            <div class="box_left">
                <img src="img/avocat.jpg" class="box_image" alt="miniature" />
            </div>


            <div class="box_right">
                <ul class="box_ul">
                    <li class="box_li">AVOCAT</li>
                    <li>LEGUMES</li>
                    <li>PLACARD</li>
                </ul>
            </div>
        </div>


        <div class="box_main">
            <div>DATE</div>
            <div>DLC</div>
        </div>

        <div class="box_bas">
            <table class="box_table">
                <tr>
                    <td class="box_td">Ajouté le 20/03/2020</td>
                </tr>
                <tr>
                    <td class="box_td">Modifié le 20/04/2020</td>


                </tr>

            </table>
            <div class="box_button">
            <button type="button" class="button styled">Modif</button>
            <button type="button" class="button styled">Suppr</button>
</div>
        </div>

    </div>

</body>

</html>