<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>FreshFood-Detais</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="css/details.css" rel="stylesheet">
</head>

<body>

    <div class="box">
        <div class="haut">

            <div class="box_left">
            <img src="img/avocat.jpg" class="image" alt="miniature" />
        </div>


            <div class="box_right">
                <ul>
                    <li>AVOCAT</li>
                    <li>LEGUMES</li>
                    <li>PLACARD</li>
                </ul>
            </div>
        </div>
        

        <div class="main">
            <div>DATE</div>
            <div>DLC</div>
        </div>

        <div class="bas">
            <table>
                <tr>
                    <td>Ajouté le 20/03/2020</td>
                </tr>
                <tr>
                    <td>Modifié le 20/04/2020</td>
                    <td><form><button type="button">Modif</button></form></td>
                    <td><form><button type="button">Suppr</button></form></td>
                </tr>

            </table>
        </div>

    </div>

</body>

</html>