        <footer class="footer">
            <div class="footer__credit">
                <div class="footer__title">Fresh Food</div>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam earum minima quod, maxime itaque quibusdam tenetur molestiae cupiditate. Illum ipsa architecto voluptatibus hic explicabo nemo magni soluta illo sapiente consequuntur.</p>
            </div>
            <div class="footer__social">
                <a href="#" title="Nous suivre sur Facebook">
                    <svg class="icon">
                        <use xlink:href="img/sprite.svg#facebook"></use>
                    </svg>
                </a>
                <a href="#" title="Nous suivre sur Twitter">
                    <svg class="icon">
                        <use xlink:href="img/sprite.svg#twitter"></use>
                    </svg>
                </a>
                <a href="#" title="Nous suivre sur YouTube">
                    <svg class="icon">
                        <use xlink:href="img/sprite.svg#youtube"></use>
                    </svg>
                </a>
            </div>
            <div class="footer__col">
                <ul>
                    <li><a href="#">Mes achats</a></li>
                    <li><a href="#">Nouveau produit</a></li>
                    <li><a href="#">Mes produits</a></li>
                    <li><a href="#">Mon stock</a></li>
                    <li><a href="#">Connexion</a></li>
                </ul>
            </div>
            <div class="footer__col">
                <div class="footer__title">Nous contactez</div>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consectetur et maiores modi amet accusamus aperiam temporibus nobis ipsa error fugit laboriosam, mollitia perspiciatis voluptatum quos. Enim ea cupiditate fugit culpa!</p>
            </div>
        </footer>
    </body>
</html>
    