<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/style.css">
    <title>Formulaire forgot password</title>
</head>
<body class="passWordForget">
<svg class="icon">
	<use xlink:href="img/sprite.svg#logo"></use>
	</svg>
    <form class="form-group">
        <h3 class="ForgotPass">FRESH FOOD</h3>
        <div class="mail1">
            <label for="email1"></label>
            <input type="email1" name="email1" class="form-text text-muted" id="mail1"  placeholder="Enter email">
        </div>
        <h6 class="lien2__forgotpass">Vous avez un compte?<a href="">Connectez-vous</a></h6>
        <div>
            <button type="submit1" class="" id="buttForgotPass" >Récupérer</button>
        </div>
    </form>
</body>
</html>
