<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/style.css">
    <title>Formulairesignin</title>
</head>
<body class="body__signin">
    <svg class="icon">
	<use xlink:href="img/sprite.svg#logo"></use>
	</svg>
    <form class="form__signIn">
        <h3 class="fresh_signinnn">FRESH FOOD</h3>
        <div class="mail">
            <label for="email"></label>
            <input type="email" id="email__signin"  placeholder="Enter email">
        </div>
        <div class="pass">
            <label for="password"></label>
            <input type="password" id="password__signin" placeholder="Password" required>
        </div>
        <h6 class="lien__signin">Vous n'avez pas de compte?<a href="">Inscrivez-vous</a></h6>
        <div>
            <button type="submit" class="butt__signin">Se connecter</button>
        </div>
    </form>    

</body>
</html>
