<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/style.css">
    <title>Formulairesignup</title>
</head>
<body>
    <form class="form2"> 
        <h3>FRESH FOOD</h3>
        <div class="thename">
            <label for="name"></label>
            <input type="text"  id="fullname" placeholder="Nom complet">
        </div>
        <div class="mail">
            <label for="email"></label>
            <input type="email" name="email" id="mail"  placeholder="Enter email">
        </div>
        <div class="myadress">
            <label for="address"></label>
            <input type="address" name="address" id="adresse" placeholder="Numéro et nom de la Rue">   
        </div>
        <div class="form-row">
            <label for="inputZip"></label>
            <input type="text" class="form-control" id="inputZip" placeholder="code postal">
            <label for="inputCity"></label>
            <input type="text" class="form-control" id="inputCity" placeholder="Ville">
        </div>
        <div class="mynumber">
            <label for="phone"></label>
            <input type="tel" name="telNo" id="phone" placeholder="Entrer numéro de télephone">
        </div>
        <div class="pass">
            <label for="password"></label>
            <input type="password" id="pass" placeholder="Password" required>
        </div>
        <h6>Vous avez déja un compte?<a href="">Connectez-vous</a></h6>
        <div>
        <button type="submit" class="connect">Se connecter</button>
        </div>
      </form>
</body>
</html>
