<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/style.css">
    <script src="js/main.js" defer></script>
    <title>Fresh Food</title>
</head>
<body>
    <header class="header">
        <div class="header__block">
            <h1 class="header__title">Bienvenue sur Fresh Food !</h1>
            <p class="header__text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis odio soluta animi quod corporis earum veritatis sunt provident, adipisci voluptate, asperiores, voluptates in consequatur autem. Voluptatem culpa quisquam facilis nobis.</p>
            <button type="button" class="header__btn">C'est parti !</button>
        </div>
    </header>
</body>
</html>