<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/style.css">
    <title>Ajouter un produit</title>
</head>

<body>
    <form action="">
        <div class="form-group">
            <label for="category">Catégorie</label>
            <select id="category" name="category">
                <option>Aucune</option>
                <option>Fruits</option>
                <option>Légumes</option>
                <option>Viandes</option>
                <option>Poissons</option>
                <option>Fruits de mer et crustacés</option>
                <option>Pain et céréales</option>
                <option>Céréales et fécuents</option>
                <option>Produits laitiers</option>
                <option>Désserts et sucré</option>
                <option>PLats préparés et snacks</option>
                <option>Condiments et épices</option>
                <option>Boissons</option>
            </select>
        </div>
        <div class="form-group">
            <label for="name">Intitulé</label>
            <input type="text" id="name" name="name">
        </div>
        <div class="form-group">
            <label for="place">Emplacement</label>
            <select id="place" name="place">
                <option>Réfrigirateur</option>
                <option>Congélateur</option>
                <option>Garde-manger</option>
                <option>Comptoir</option>
                <option>Placard</option>
                <option>Cave</option>
            </select>
        </div>
        <div class="form-group">
            <label for="quantity">Quantité</label>
            <input type="number" name="quantity" id="quantity">
        </div>
        <div class="form-group">
            <label for="unity">Unité</label>
            <select id="unity" name="unity">
                <option>Pas d'unité</option>
                <option>morceau(x)</option>
                <option>paquet(s)</option>
                <option>boîte(s)</option>
                <option>sachet(s)</option>
                <option>g</option>
                <option>Kg</option>
                <option>bouteille(s)</option>
                <option>canette(s)</option>
                <option>L</option>
                <option>mL</option>
            </select>
        </div>
        <div class="form-group">
            <label for="date">Date d'achat</label>
            <input type="datetime" name="date" id="date">
        </div>
    </form>
</body>

</html>